version: '3.8'

services:
  scraping-job-config-db:
    image: postgres:latest
    container_name: scraping-job-config-db
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: spring_batch_db
    ports:
      - "5433:5432"
    networks:
      - scraping-network

  scraping-universe:
    image: fmahmud26/scraping-universe:v2024.9.1
    container_name: scraping-universe
    ports:
      - "8082:8080"
    depends_on:
      - scraping-job-config-db
    networks:
      - scraping-network

networks:
  scraping-network:
    driver: bridge
